var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return $jscomp.arrayIterator(a);throw Error(String(a)+" is not an iterable or ArrayLike");};
function resize_svg$$module$Input_0(a,b){var d=d3.select("#"+a+" svg").node(),c=d.viewBox.baseVal.width;d=d.viewBox.baseVal.height;var e=d3.select("#"+a+" svg g").node().getBBox();c=c/2-(e.x+e.width/2)*b;d=d/2-(e.y+e.height/2)*b;d3.select("#"+a+" svg g").attr("transform","translate("+c+", "+d+") scale("+b+")")}
function scale_svgs$$module$Input_0(a,b,d){if(2===b){if(b=a[0],a=a[1],console.log(b,a),1>b&&1>a){var c=Math.max(b,a);b<c?resize_svg$$module$Input_0(d+"-1",b/c):a<c&&resize_svg$$module$Input_0(d+"-2",a/c)}}else if(3===b&&(b=a[0],c=a[1],a=a[2],console.log(b,c,a),1>b&&1>c&&1>a)){var e=Math.max(b,c,a);b<e&&resize_svg$$module$Input_0(d+"-1",b/e);c<e&&resize_svg$$module$Input_0(d+"-2",c/e);a<e&&resize_svg$$module$Input_0(d+"-3",a/e)}}
var tab_create_viz$$module$Input_0=function(a,b){if("tab2"===b)clearVisualization$$module$Input_0(a+"-1"),create_viz$$module$Input_0(a+"-1","tb2-text-input","tb2-sidebar");else if("tab3"===b){clearVisualization$$module$Input_0(a+"-1");clearVisualization$$module$Input_0(a+"-2");var d=document.getElementById("tb3-visualization-combined-export-btn");null!==d&&d.remove();d=create_viz$$module$Input_0(a+"-1","tb3-text-input-1","tb3-sidebar-1");var c=create_viz$$module$Input_0(a+"-2","tb3-text-input-2",
"tb3-sidebar-2");scale_svgs$$module$Input_0([d,c],2,a);addDownloadCombinedButton$$module$Input_0(a,a+"-1")}else if("tab4"===b){clearVisualization$$module$Input_0(a+"-1");clearVisualization$$module$Input_0(a+"-2");clearVisualization$$module$Input_0(a+"-3");d=document.getElementById("tb4-visualization-combined-export-btn");null!==d&&d.remove();d=create_viz$$module$Input_0(a+"-1","tb4-text-input-1","tb4-sidebar-1");c=create_viz$$module$Input_0(a+"-2","tb4-text-input-2","tb4-sidebar-2");var e=create_viz$$module$Input_0(a+
"-3","tb4-text-input-3","tb4-sidebar-3");scale_svgs$$module$Input_0([d,c,e],3,a);addDownloadCombinedButton$$module$Input_0(a,a+"-1",3)}};function darkenColor$$module$Input_0(a){a=d3.hsl(a);a.l-=.2;a.l=Math.max(0,Math.min(1,a.l));return d3.rgb(a).toString()}var visualizations$$module$Input_0=document.querySelectorAll(".visualization");visualizations$$module$Input_0.forEach(function(a){a.style.display="none"});var clearVisualization$$module$Input_0=function(a){for(a=document.querySelector("#"+a);a.firstChild;)a.removeChild(a.firstChild)};
function getPaddedBBox$$module$Input_0(a,b){var d=a.getBBox();return{x:d.x-b,y:d.y-b,width:d.width+2*b,height:d.height+2*b}}
var findNonOverlappingRegion$$module$Input_0=function(a,b,d,c,e,f,l,p){f*=3.5;var m=a.selectAll("text").filter(function(){return this!==p});a=d+f;d-=f;var r=b-c/2;f=function(z){var B=0;m.each(function(){var t=getPaddedBBox$$module$Input_0(this,l);r+c>t.x&&r<t.x+t.width&&(z+e>t.y&&z<t.y+t.height||z-e>t.y&&z-e<t.y+t.height)&&B++});return B};b=f(a);f=f(d);return{x:r,y:b===f?.5>Math.random()?a:d:b<f?a:d}},create_viz$$module$Input_0=function(a,b,d,c,e,f){c=void 0===c?40:c;e=void 0===e?600:e;f=void 0===
f?335:f;b=document.querySelector("#"+b);d=document.querySelector("#"+d);f=d3.select("#"+a).append("svg").attr("width","100%").attr("height","100%").attr("viewBox","0 0 "+e+" "+f).attr("preserveAspectRatio","xMidYMid meet");var l=f.append("g");b=Array.from(b.childNodes);var p={};d.querySelectorAll('.item-wrapper:not([data-type="horizontal-line"])').forEach(function(g){var E=g.querySelector(".color-index-container").id.slice(-6),q=g.querySelectorAll(".color-description-input"),u=g.querySelectorAll(".description-dropdown");
g=Array.from(q).map(function(w,n){return((""!=u[n].value?u[n].value+": ":"")+" "+w.value).trim()}).join("\n");p[E]=g});var m=0,r=20,z=10*c,B=new Set,t=[],L=[];b.forEach(function(g,E){if(g.nodeType===Node.TEXT_NODE)g.textContent.split(" ").forEach(function(C){var D=l.append("text").attr("x",-9999).attr("y",-9999).text(C),x=D.node().getComputedTextLength();D.remove();m+x>z&&(m=0,r+=35);l.append("text").attr("x",m).attr("y",r).text(C);t.push(m);m+=x+5});else if(g.nodeType===Node.ELEMENT_NODE){var q=
g.className.slice(-6),u=g.className.includes("color-highlight"),w=g.className.includes("strikethrough"),n=g.textContent.split(" "),y=Math.floor((n.length+1)/2)-1,v;n.forEach(function(C,D){var x=l.append("text").attr("x",-9999).attr("y",-9999).text(C),A=x.node().getComputedTextLength();x.remove();m+A>z&&(m=0,r+=35);D===y&&(v=m);l.append("text").attr("x",m).attr("y",r).text(C).style("pointer-events","none");D===y&&(v=m+A/2);u&&l.insert("rect","text").attr("x",m-3).attr("y",r-15).attr("width",A+6).attr("height",
20).attr("fill","#"+q);w&&l.insert("line","text").attr("x1",m-3).attr("y1",r-5).attr("x2",m+A+2).attr("y2",r-5).attr("stroke","#"+q).attr("stroke-width",2);m+=A+5});p[q]&&!B.has(g)&&(B.add(g),L.push({color:q,middleWordX:v,currentY:r,annotationLines:p[q].split("\n")}))}});L.filter(function(g){return g.annotationLines.some(function(E){return""!==E.trim()})}).forEach(function(g){var E=g.color,q=g.middleWordX,u=g.currentY,w=g.annotationLines;g=l.append("g").on("mouseover",function(){showDragHandles$$module$Input_0(d3.select(this))}).on("mouseout",
function(){hideDragHandles$$module$Input_0(d3.select(this))}).on("touchstart",function(){showDragHandles$$module$Input_0(d3.select(this))});var n=g.append("text").attr("x",q-6).attr("y",u).style("fill",darkenColor$$module$Input_0("#"+E)).style("font-size","14px").style("pointer-events","none");w.forEach(function(h,k){n.append("tspan").text(h).attr("x",q-6).attr("dy",0===k?0:20)});w=getPaddedBBox$$module$Input_0(n.node(),5);w=findNonOverlappingRegion$$module$Input_0(l,q,u,w.width,w.height,20,5,n.node());
n.attr("x",w.x).attr("y",w.y);n.selectAll("tspan").attr("x",w.x);var y=getPaddedBBox$$module$Input_0(n.node(),5),v=y.x,C=y.x+y.width,D=y.y;y=y.y+y.height;v=[{x:v,y:(D+y)/2},{x:C,y:(D+y)/2},{x:(v+C)/2,y:D},{x:(v+C)/2,y:y}].reduce(function(h,k){return Math.sqrt(Math.pow(k.x-q,2)+Math.pow(k.y-u,2))<Math.sqrt(Math.pow(h.x-q,2)+Math.pow(h.y-u,2))?k:h});var x=g.append("line").attr("x1",q-6).attr("y1",u).attr("x2",v.x).attr("y2",v.y).attr("stroke",darkenColor$$module$Input_0("#"+E)).attr("stroke-width",
1.5),A=g.append("circle").attr("cx",v.x).attr("cy",v.y).attr("r",3).attr("fill",darkenColor$$module$Input_0("#"+E));w.y<u?n.attr("y",parseFloat(n.attr("y"))-5):n.attr("y",parseFloat(n.attr("y"))+5);var G=g.append("circle").attr("class","drag-handle draggable").attr("cx",v.x).attr("cy",v.y).attr("r",4).attr("fill","blue").style("cursor","move").style("display","none");G.call(createDragBehavior$$module$Input_0(function(h,k){G.attr("cx",parseFloat(G.attr("cx"))+h).attr("cy",parseFloat(G.attr("cy"))+
k);var F=parseFloat(n.attr("x"))+h,H=parseFloat(n.attr("y"))+k;n.attr("x",F).attr("y",H);n.selectAll("tspan").attr("x",F);x.attr("x2",parseFloat(x.attr("x2"))+h).attr("y2",parseFloat(x.attr("y2"))+k);A.attr("cx",parseFloat(A.attr("cx"))+h).attr("cy",parseFloat(A.attr("cy"))+k)},function(){var h=getPaddedBBox$$module$Input_0(n.node(),5),k=h.x,F=h.x+h.width,H=h.y;h=h.y+h.height;k=[{x:k,y:(H+h)/2},{x:F,y:(H+h)/2},{x:(k+F)/2,y:H},{x:(k+F)/2,y:h}].reduce(function(J,K){return Math.sqrt(Math.pow(K.x-q,2)+
Math.pow(K.y-u,2))<Math.sqrt(Math.pow(J.x-q,2)+Math.pow(J.y-u,2))?K:J});x.attr("x2",k.x).attr("y2",k.y);A.attr("cx",k.x).attr("cy",k.y);G.attr("cx",k.x).attr("cy",k.y)}));var I=g.append("circle").attr("class","drag-handle draggable").attr("cx",q-6).attr("cy",u).attr("r",4).attr("fill","blue").style("cursor","move").style("display","none");I.call(createDragBehavior$$module$Input_0(function(h,k){x.attr("x1",parseFloat(x.attr("x1"))+h).attr("y1",parseFloat(x.attr("y1"))+k);I.attr("cx",parseFloat(I.attr("cx"))+
h).attr("cy",parseFloat(I.attr("cy"))+k)},function(){}))});c=l.node().getBBox();f.attr("viewBox","0 0 "+(c.width+40)+" "+(c.height+40));l.attr("transform","translate("+(20-c.x)+", "+(20-c.y)+")");addDownloadButton$$module$Input_0(f,a);return(c.width+40)/e};function createDragBehavior$$module$Input_0(a,b){var d=this,c,e;return d3.drag().on("start",function(f){f.sourceEvent.stopPropagation();c=f.x;e=f.y}).on("drag",function(f){var l=f.x-c,p=f.y-e;c=f.x;e=f.y;a.call(d,l,p)}).on("end",b)}
function showDragHandles$$module$Input_0(a){a.selectAll(".drag-handle").style("display","block")}function hideDragHandles$$module$Input_0(a){a.selectAll(".drag-handle").style("display","none")}function addDownloadButton$$module$Input_0(a,b){var d=document.getElementById(b),c=document.createElement("button");c.className="download-svg-btn";c.id=b+"-export-btn";c.innerHTML='\n  <i class="fas fa-file-download"></i>';c.onclick=function(){downloadVisualization$$module$Input_0(a)};d.appendChild(c)}
function addDownloadCombinedButton$$module$Input_0(a,b,d){d=void 0===d?2:d;b=document.getElementById(b);var c=document.createElement("button");c.className="download-svg-combined-btn";c.id=a+"-combined-export-btn";2==d?c.innerHTML='\n  <i class="fas fa-file-download"></i><i class="fas fa-plus"></i><i class="fas fa-file-download"></i>':3==d&&(c.innerHTML='\n  <i class="fas fa-file-download"></i><i class="fas fa-plus"></i><i class="fas fa-file-download"></i><i class="fas fa-plus"></i><i class="fas fa-file-download"></i>');
c.onclick=function(){downloadCombinedVisualizations$$module$Input_0(a)};b.appendChild(c)}
function downloadVisualization$$module$Input_0(a){var b=a.node().cloneNode(!0);includeStyles$$module$Input_0(b);a=getSVGContentBoundingBox$$module$Input_0(a);b.setAttribute("viewBox",a.x+" "+a.y+" "+a.width+" "+a.height);a=(new XMLSerializer).serializeToString(b);a="data:image/svg+xml;base64,"+btoa(unescape(encodeURIComponent(a)));b=b.getAttribute("viewBox").split(" ").map(parseFloat);b=1200/(b[2]/b[3]);var d=new Image;d.src=a;var c=document.createElement("canvas");c.width=1200;c.height=b;var e=c.getContext("2d");
d.onload=function(){e.drawImage(d,0,0,c.width,c.height);var f=c.toDataURL("image/png"),l=document.createElement("a");l.href=f;l.download="visualization.png";l.click()}}
function includeStyles$$module$Input_0(a){var b=document.styleSheets,d=document.createElement("style"),c="";b=$jscomp.makeIterator(b);for(var e=b.next();!e.done;e=b.next()){e=e.value;var f=void 0;try{f=e.rules||e.cssRules}catch(l){continue}e=$jscomp.makeIterator(f);for(f=e.next();!f.done;f=e.next())c+=f.value.cssText+"\n"}d.innerHTML=c;a.insertBefore(d,a.firstChild)}function getSVGContentBoundingBox$$module$Input_0(a){return a.select("g").node().parentNode.getBBox()}
function downloadCombinedVisualizations$$module$Input_0(a){a=document.getElementById(a);var b=Array.from(a.querySelectorAll(".subvisualization"));a=335*b.length;var d=document.createElement("canvas");d.width=600;d.height=a;var c=d.getContext("2d"),e=0;b.forEach(function(f,l){var p=f.querySelector("svg"),m=p.cloneNode(!0),r=600/p.clientWidth*p.clientHeight;m.setAttribute("width",600);m.setAttribute("height",r);console.log(m);var z=new Image;z.onload=function(){c.drawImage(z,0,e,600,r);e+=r;if(l===
b.length-1){var B=d.toDataURL("image/png"),t=document.createElement("a");t.href=B;t.download="combined_visualization.png";t.click()}};z.onerror=function(B){console.error("Error loading image "+l+":",B)};p=(new XMLSerializer).serializeToString(m);p=new Blob([p],{type:"image/svg+xml"});p=URL.createObjectURL(p);z.src=p})}var module$Input_0={tab_create_viz:tab_create_viz$$module$Input_0};
